# Generated by Django 4.1.4 on 2022-12-13 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='is_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
