# Generated by Django 4.1.4 on 2022-12-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_user_followed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(default=None, max_length=140),
        ),
    ]
